server:
  port: 8083
spring:
  application:
    name: artist-service
  datasource:
    url: jdbc:h2:mem:maindb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
