server:
  port: 8089
spring:
  application:
    name: booking-service
  kafka:
    producer:
      bootstrap-servers: localhost:9092,localhost:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 10
      properties:
        retry.backoff.ms: 1000
        enable.idempotence: true
        delivery.timeout.ms: 20000
        request.timeout.ms: 10000
        spring.json.trusted.packages: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
