spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql:
    show-sql: true
    database: postgresql

  application:
    name: identity-service

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 8085
jwt:
  secret: "E38FAC7A1631103FA4A4670A8749EE01062B937DC639E88F933BD3691CA0C116"
